apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amq-broker
spec:
  serviceName: "amq-broker-2"
  selector:
    matchLabels:
      app: amq-broker-2
  template:
    spec:
      containers:
        - name: activemq-artemis
          env:
            - name: AMQ_NAME
              value: amq-broker-1
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: amq-broker-2
