apiVersion: v1
kind: ConfigMap
metadata:
  name: amq-broker-auth
data:
  login.config: |
    OpenShiftLogin {
      io.fabric8.openshift.auth.OpenShiftLoginModule required;
        roleAttribute="roles"
        validateUser=true
        validateRoles=true;
    };
