apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: broker-config
    files:
      - broker.xml

resources:
  - configmap.yaml
  - oauthclient.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
  - statefulset.yaml
