apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-1-amq-broker-2
spec:
  project: default
  source:
    repoURL: https://github.com/cziesman/amq-broker.git
    targetRevision: main
    path: gitops/manifests/app/overlays/environment-1/broker-2
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
