apiVersion: v1
kind: ConfigMap
metadata:
  name: amq-broker
data:
  broker.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration xmlns="urn:activemq">
        <core>
            <name>AMQ Broker 2</name>
            <paging-directory>/var/lib/artemis/data/paging</paging-directory>
            <bindings-directory>/var/lib/artemis/data/bindings</bindings-directory>
            <journal-directory>/var/lib/artemis/data/journal</journal-directory>
            <large-messages-directory>/var/lib/artemis/data/large-messages</large-messages-directory>
            <acceptors>     
                <acceptor name="amqp">tcp://0.0.0.0:6672</acceptor>
                <acceptor name="stomp">tcp://0.0.0.0:63613</acceptor>
                <acceptor name="openwire">tcp://0.0.0.0:63616</acceptor>
                <acceptor name="mqtt">tcp://0.0.0.0:2883</acceptor>
                <acceptor name="http">http://0.0.0.0:8180</acceptor>
                <acceptor name="ws">ws://0.0.0.0:62614</acceptor>
                <acceptor name="console">http://0.0.0.0:8261</acceptor>
    
                <acceptor name="https">https://0.0.0.0:8444</acceptor>
                <acceptor name="amqp-ssl">tcp://0.0.0.0:6671?sslEnabled=true</acceptor>
                <acceptor name="stomp-ssl">tcp://0.0.0.0:62617?sslEnabled=true</acceptor>
                <acceptor name="openwire-ssl">tcp://0.0.0.0:62618?sslEnabled=true</acceptor>
                <acceptor name="mqtt-ssl">tcp://0.0.0.0:8884?sslEnabled=true</acceptor>
                <acceptor name="ws-ssl">wss://0.0.0.0:62619?sslEnabled=true</acceptor>
            </acceptors>
        </core>
    </configuration>
