apiVersion: kustomize.config.k8s.io/v2beta2
kind: Kustomization

namespace: amq

nameSuffix: "-2"

commonLabels:
  app: amq-broker-2

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: pvc-patch.yaml
  - path: route-patch.yaml
  - path: service-patch.yaml
  - path: statefulset-patch.yaml
