apiVersion: v1
kind: Service
metadata:
  name: amq-broker
spec:
  selector:
    app: amq-broker-2
  ports:
    - name: core-messaging-2
      port: 62616
      targetPort: 61616
    - name: web-console-2
      port: 8261
      targetPort: 8161
    - name: amqp-2
      port: 6672
      targetPort: 5672
    - name: mqtt-2
      port: 2883
      targetPort: 1883
    - name: stomp-2
      port: 62613
      targetPort: 61613
