apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amq-broker
spec:
  serviceName: "amq-broker-2"
  selector:
    matchLabels:
      app: amq-broker-2
  template:
    spec:
      containers:
        - name: activemq-artemis
          env:
            - name: AMQ_NAME
              value: amq-broker-1
          ports:
            - containerPort: 62616
              name: openwire
            - containerPort: 8261
              name: console
            - containerPort: 6672
              name: amqp
            - containerPort: 2883
              name: mqtt
            - containerPort: 62613
              name: stomp
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: amq-broker-2
        - name: broker-config
          configMap:
            name: amq-broker-2
