kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
