apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amq-broker
spec:
  serviceName: "amq-broker"
  replicas: 1
  selector:
    matchLabels:
      app: amq-broker
  template:
    metadata:
      labels:
        app: amq-broker
    spec:
      containers:
        - name: activemq-artemis
          image: registry.redhat.io/amq7/amq-broker-rhel8:<version>
          ports:
            - containerPort: 61616
            - containerPort: 8161
          volumeMounts:
            - name: broker-storage
              mountPath: /var/lib/artemis/data
            - name: broker-config
              mountPath: /var/lib/artemis/etc/broker.xml
              subPath: broker.xml
      volumes:
        - name: broker-config
          configMap:
            name: amq-broker-config
