apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../common
  -
resources:
  - ../../../../base

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: amq-broker-1
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
