apiVersion: v1
kind: ConfigMap
metadata:
  name: amq-broker
data:
  broker.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration xmlns="urn:activemq">
        <core>
            <name>AMQ Broker 1</name>
            <paging-directory>/var/lib/artemis/data/paging</paging-directory>
            <bindings-directory>/var/lib/artemis/data/bindings</bindings-directory>
            <journal-directory>/var/lib/artemis/data/journal</journal-directory>
            <large-messages-directory>/var/lib/artemis/data/large-messages</large-messages-directory>
            <acceptors>
                <acceptor name="amqp">tcp://0.0.0.0:5672</acceptor>
                <acceptor name="stomp">tcp://0.0.0.0:61613</acceptor>
                <acceptor name="openwire">tcp://0.0.0.0:61616</acceptor>
                <acceptor name="mqtt">tcp://0.0.0.0:1883</acceptor>
                <acceptor name="http">http://0.0.0.0:8080</acceptor>
                <acceptor name="ws">ws://0.0.0.0:61614</acceptor>
                <acceptor name="console">http://0.0.0.0:8161</acceptor>
    
                <acceptor name="https">https://0.0.0.0:8443</acceptor>
                <acceptor name="amqp-ssl">tcp://0.0.0.0:5671?sslEnabled=true</acceptor>
                <acceptor name="stomp-ssl">tcp://0.0.0.0:61617?sslEnabled=true</acceptor>
                <acceptor name="openwire-ssl">tcp://0.0.0.0:61618?sslEnabled=true</acceptor>
                <acceptor name="mqtt-ssl">tcp://0.0.0.0:8883?sslEnabled=true</acceptor>
                <acceptor name="ws-ssl">wss://0.0.0.0:61619?sslEnabled=true</acceptor>
            </acceptors>
        </core>
    </configuration>
