apiVersion: v1
kind: Service
metadata:
  name: amq-broker
spec:
  selector:
    app: amq-broker-1
  ports:
    - name: core-messaging
      port: 61616
      targetPort: 61616
    - name: web-console
      port: 8161
      targetPort: 8161
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: stomp
      port: 61613
      targetPort: 61613
    - name: clustering
      port: 7800
      targetPort: 7800
  type: ClusterIP
