apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amq-broker
spec:
  serviceName: "amq-broker-1"
  selector:
    matchLabels:
      app: amq-broker-1
  template:
    spec:
      containers:
        - env:
            - AMQ_USER=redhat
            - AMQ_PASSWORD=redhat
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: amq-broker-1
        - name: broker-config
          configMap:
            name: amq-broker-1
