apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-demo

nameSuffix: "-1"

labels:
  - includeSelectors: true
    pairs:
      app: amq-broker-1

resources:
  - ../../../../base

patches:
  - path: pvc-patch.yaml
  - path: route-patch.yaml
  - path: service-patch.yaml
  - path: statefulset-patch.yaml
