apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-1-amq-broker-1
spec:
  project: default
  source:
    repoURL: https://github.com/cziesman/amq-broker.git
    targetRevision: main
    path: gitops/manifests/app/overlays/environment-1/broker-1/common
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "*"
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
